Local ros packages as dependency
rosie-project/rosie_ros2_deps pull request #1
Opened 2022-06-10 10:35 UTC by dagyu

Currently to create custom srv, msg and action you can do it by adding the files on the source directory but in this way non-standard interfaces are created which can cause some problems
* the introspection tools provided by ros2 such as rqt or cli commands cannot be used
* if the same interface is used by both ROSiE and rclpy or rclcpp then the interface definition must be duplicated twice

To solve these problems I have added the ability to define a locally installed package by adding {ros_pkg_name, {ros2, local}} to the rebar.config.

Under the hood `ros2 pkg prefix ros_pkg_name` is used to find interfaces files cb4f102064219089bee76a488ce0773cfb1d4ae3.

In addition, the way in which information on rebar.lock is stored has also been changed 69f2d4147209dae45b0fcb9c01d9a02f7a40e4ab to allow packages to be updated if the local version of the package is updated with respect to the one installed in the _build folder.

2022-06-10 13:54 UTC, ziopio commented
> 
>     * the introspection tools provided by ros2 such as rqt or cli commands cannot be used
> 
Really? Then there is a bug in the implementation somewhere... In all tests i've done, even recently in CODEBEAM 2022 i was always able to introspect my ROSiE nodes through RQT, RVIZ2 and the CLI.


>     * if the same interface is used by both ROSiE and rclpy or rclcpp then the interface definition must be duplicated twice
> 
Well this is only a real problem if you are developing a native ros2 package (not available in any distro) locally and want to test it in a ROSiE project. Which in you very particular use case may be really needed and it's fine.

2022-06-10 15:33 UTC, dagyu commented
> Really? Then there is a bug in the implementation somewhere... In all tests i've done, even recently in CODEBEAM 2022 i was always able to introspect my ROSiE nodes through RQT, RVIZ2 and the CLI. Maybe you mean the tools related to package inspection... well those of course are desirable if i understand what you want to do.

I'm talking about the case when you work with custom interfaces and when I say introspection tools cannot be used I mean in those cases when you do something that needs serialization and deserialization of interfaces, here are some examples of cli commands that don't work with custom interfaces:

* `ros2 interface show my_custom_interface`
* `ros2 action send_goal custom_action_name my_custom_interface "parameters"`

Obviously all the other commands or tools that do not need to serialize or deserialize the custom interface data will continue to work well. 

> Well this is only a real problem if you are developing a native ros2 package (not available in any distro) locally and want to test it in a ROSiE project. Which in your very particular use case may be really needed and it's fine

Yes, It is useful if you want to use any package (not necessarily developed by me) not present in the ros2 galactic distro (currently the only one supported)

2022-06-13 07:23 UTC, ziopio requested changes
I'm going to merge this PR, but before that i would suggest to remove `erlfmt`.

The formatter is fine but i would rather put it in ~/.config/rebar3/rebar.config.
In this way you can use it where ever you want without having it downloaded for every project.

2022-06-13 07:23 UTC, ziopio commented on rebar.config
> +{plugins, [erlfmt]}.
Just so you know... I just removed erlfmt from all repositories because i find it not really usefull as a dependancy. Usually if i want to auto format now, i just rely on my VScode. But since most of the time I format manually, i preferred to not have to compile `erlfmt` as a project dep.

I think is more "clean" to have this plugin installed globally in your system and use it once in a while, instead of having it as project dep.

2022-06-13 07:23 UTC, ziopio commented on src/rosie_ros2_resource.erl
> +    end.
Cool, we could also do this check for the non-local package version.
It should be reported in the distribution.yaml file...
So the plugin can re-download if a new version is out.

I would be nice to lock/unlock and upgrade ROSiE deps.

2022-06-14 14:42 UTC, dagyu commented on rebar.config
> +{plugins, [erlfmt]}.
`erlfmt` is not a project dependency but a plugin dependency that is pretty different anyway I removed it from `rebar.config` as you suggested. 

To get better contributions my suggestion is to have some configuration files inside the repo, if you use VsCode for example you can add a `.vscode` dir with all the configurations, in this way everyone that fetch the repo share the same configurations. Something like:

`.vscode/settings.json` to configure the formatter
```json
{
  "[erlang]": {
    "editor.defaultFormatter": "szTheory.erlang-formatter",
    "editor.formatOnSave": true
  },
  "erlangFormatter.formatter": "erlfmt",
}
```
`.vscode/extension.json` to recomends installation of the formatter
```json
{
  "recommendations" : [
    "szTheory.erlang-formatter"
  ]
}
```

2022-06-14 14:44 UTC, dagyu commented on src/rosie_ros2_resource.erl
> +    end.
Yes, of course it is an excellent suggestion but is out of the scope of this PR, I think it would be better to create an issue

2022-06-14 15:13 UTC, ziopio commented on rebar.config
> +{plugins, [erlfmt]}.
Oh God, i don't want to begin a discussion about formatting... next time ahah 
Thank you for the cool json btw...

2022-06-14 15:13 UTC, merged